ALTER TABLE eve_item_table AUTO_INCREMENT = 1;

INSERT INTO eve_item_table (`category_id`, `type_id`, `item_name`) VALUES
    (1,1,'Veldspar'),
    (1,1,'Concentrated Veldspar'),
    (1,1,'Dense Veldspar'),
    (1,2,'Scordite'),
    (1,2,'Condensed Scordite'),
    (1,2,'Massive Scordite'),
    (1,3,'Plagioclase'),
    (1,3,'Azure Plagioclase'),
    (1,3,'Rich Plagioclase'),
    (1,4,'Pyroxeres'),
    (1,4,'Solid Pyroxeres'),
    (1,4,'Viscous Pyroxeres'),
    (1,5,'Omber'),
    (1,5,'Silvery Omber'),
    (1,5,'Golden Omber'),
    (1,6,'Kernite'),
    (1,6,'Luminous Kernite'),
    (1,6,'Fiery Kernite'),
    (1,7,'Jaspet'),
    (1,7,'Pure Jaspet'),
    (1,7,'Pristine Jaspet'),
    (1,8,'Hemorphite'),
    (1,8,'Vivid Hemorphite'),
    (1,8,'Radiant Hemorphite'),
    (1,9,'Hedbergite'),
    (1,9,'Vitric Hedbergite'),
    (1,9,'Glazed Hedbergite'),
    (1,10,'Gneiss'),
    (1,10,'Iridescent Gneiss'),
    (1,10,'Prismatic Gneiss'),
    (1,11,'Dark Ochre'),
    (1,11,'Onyx Ochre'),
    (1,11,'Obsidian Ochre'),
    (1,12,'Crokite'),
    (1,12,'Sharp Crokite'),
    (1,12,'Crystalline Crokite'),
    (1,13,'Spodumain'),
    (1,13,'Bright Spodumain'),
    (1,13,'Gleaming Spodumain'),
    (1,14,'Bistot'),
    (1,14,'Triclinic Bistot'),
    (1,14,'Monoclinic Bistot'),
    (1,15,'Arkonor'),
    (1,15,'Crimson Arkonor'),
    (1,15,'Prime Arkonor'),
    (1,16,'Mercoxit'),
    (1,16,'Magma Mercoxit'),
    (1,16,'Vitreous Mercoxit'),
    (1,17,'Tritanium'),
    (1,17,'Pyerite'),
    (1,17,'Mexallon'),
    (1,17,'Isogen'),
    (1,17,'Nocxium'),
    (1,17,'Zydrine'),
    (1,17,'Megacyte'),
    (1,17,'Morphite'),
    (7,28,'Anchoring'),
    (7,28,'CFO Training'),
    (7,28,'Corporation Management'),
    (7,28,'Empire Control'),
    (7,28,'Ethnic Relations'),
    (7,28,'Megacorp Management'),
    (7,28,'Sovereignty'),
    (7,28,'Starbase Defense Management'),
    (7,29,'Advanced Drone Interfacing'),
    (7,29,'Amarr Drone Specialization'),
    (7,29,'Caldari Drone Specialization'),
    (7,29,'Combat Drone Operations'),
    (7,29,'Drone Durability'),
    (7,29,'Drone Interfacing'),
    (7,29,'Drone Navigation'),
    (7,29,'Drone Sharpshooting'),
    (7,29,'Drones'),
    (7,29,'Electronic Warfare Drone Interfacing'),
    (7,29,'Fighters'),
    (7,29,'Gallente Drone Specialization'),
    (7,29,'Heavy Drone Operation'),
    (7,29,'Mining Drone Operation'),
    (7,29,'Minmatar Drone Specialization'),
    (7,29,'Repair Drone Operation'),
    (7,29,'Scout Drone Operations'),
    (7,29,'Sentry Drone Interfacing'),
    (7,30,'Cloaking'),
    (7,30,'Cynosural Field Theory'),
    (7,30,'Electronic Warfare'),
    (7,30,'Electronics'),
    (7,30,'Electronics Upgrades'),
    (7,30,'Frequency Modulation'),
    (7,30,'Long Distance Jamming'),
    (7,30,'Long Range Targeting'),
    (7,30,'Multitasking'),
    (7,30,'Projected Electronic Counter Measures'),
    (7,30,'Propulsion Jamming'),
    (7,30,'Sensor Linking'),
    (7,30,'Signal Dispersion'),
    (7,30,'Signal Suppression'),
    (7,30,'Signature Analysis'),
    (7,30,'Signature Focusing'),
    (7,30,'Survey'),
    (7,30,'Target Painting'),
    (7,30,'Targeting'),
    (7,30,'Turret Destabilization'),
    (7,30,'Weapon Disruption'),
    (7,31,'Capital Energy Emission Systems'),
    (7,31,'Capital Shield Emission Systems'),
    (7,31,'Capital Shield Operation'),
    (7,31,'EM Shield Compensation'),
    (7,31,'Energy Emission Systems'),
    (7,31,'Energy Grid Upgrades'),
    (7,31,'Energy Management'),
    (7,31,'Energy Pulse Weapons'),
    (7,31,'Energy Systems Operations'),
    (7,31,'Engineering'),
    (7,31,'Explosive Shield Compensation'),
    (7,31,'Kinetic Shield Compensation'),
    (7,31,'Shield Compensation'),
    (7,31,'Shield Emission Systems'),
    (7,31,'Shield Management'),
    (7,31,'Shield Operation'),
    (7,31,'Shield Upgrades'),
    (7,31,'Tactical Shield Manipulation'),
    (7,31,'Thermic Shield Compensation'),
    (7,32,'Advanced Weapon Upgrades'),
    (7,32,'Capital Energy Turret'),
    (7,32,'Capital Hybrid Turret'),
    (7,32,'Capital Projectile Turret'),
    (7,32,'Controlled Bursts'),
    (7,32,'Gunnery'),
    (7,32,'Large Artillery Specialization'),
    (7,32,'Large Autocannon Specialization'),
    (7,32,'Large Beam Laser Specialization'),
    (7,32,'Large Blaster Specialization'),
    (7,32,'Large Energy Turret'),
    (7,32,'Large Hybrid Turret'),
    (7,32,'Large Projectile Turret'),
    (7,32,'Large Pulse Laser Specialization'),
    (7,32,'Large Railgun Specialization'),
    (7,32,'Medium Artillery Specialization'),
    (7,32,'Medium Autocannon Specialization'),
    (7,32,'Medium Beam Laser Specialization'),
    (7,32,'Medium Blaster Specialization'),
    (7,32,'Medium Energy Turret'),
    (7,32,'Medium Hybrid Turret'),
    (7,32,'Medium Projectile Turret'),
    (7,32,'Medium Pulse Laser Specialization'),
    (7,32,'Medium Railgun Specialization'),
    (7,32,'Motion Prediction'),
    (7,32,'Rapid Firing'),
    (7,32,'Sharpshooter'),
    (7,32,'Small Artillery Specialization'),
    (7,32,'Small Autocannon Specialization'),
    (7,32,'Small Beam Laser Specialization'),
    (7,32,'Small Blaster Specialization'),
    (7,32,'Small Energy Turret'),
    (7,32,'Small Hybrid Turret'),
    (7,32,'Small Projectile Turret'),
    (7,32,'Small Pulse Laser Specialization'),
    (7,32,'Small Railgun Specialization'),
    (7,32,'Surgical Strike'),
    (7,32,'Tactical Weapon Reconfiguration'),
    (7,32,'Trajectory Analysis'),
    (7,32,'Weapon Upgrades'),
    (7,33,'Advanced Mass Production'),
    (7,33,'Arkonor Processing'),
    (7,33,'Bistot Processing'),
    (7,33,'Crokite Processing'),
    (7,33,'Dark Ochre Processing'),
    (7,33,'Deep Core Mining'),
    (7,33,'Drug Manufacturing'),
    (7,33,'Gas Cloud Harvesting'),
    (7,33,'Gneiss Processing'),
    (7,33,'Hedbergite Processing'),
    (7,33,'Hemorphite Processing'),
    (7,33,'Ice Harvesting'),
    (7,33,'Ice Processing'),
    (7,33,'Industrial Reconfiguration'),
    (7,33,'Industry'),
    (7,33,'Jaspet Processing'),
    (7,33,'Kernite Processing'),
    (7,33,'Mass Production'),
    (7,33,'Mercoxit Processing'),
    (7,33,'Mining'),
    (7,33,'Mining Upgrades'),
    (7,33,'Mobile Factory Operation'),
    (7,33,'Mobile Refinery Operation'),
    (7,33,'Omber Processing'),
    (7,33,'Plagioclase Processing'),
    (7,33,'Production Efficiency'),
    (7,33,'Pyroxeres Processing'),
    (7,33,'Refinery Efficiency'),
    (7,33,'Refining'),
    (7,33,'Scordite Processing'),
    (7,33,'Scrapmetal Processing'),
    (7,33,'Spodumain Processing'),
    (7,33,'Supply Chain Management'),
    (7,33,'Veldspar Processing'),
    (7,34,'Armored Warfare'),
    (7,34,'Armored Warfare Specialist'),
    (7,34,'Fleet Command'),
    (7,34,'Information Warfare'),
    (7,34,'Information Warfare Specialist'),
    (7,34,'Leadership'),
    (7,34,'Mining Director'),
    (7,34,'Mining Foreman'),
    (7,34,'Siege Warfare'),
    (7,34,'Siege Warfare Specialist'),
    (7,34,'Skirmish Warfare'),
    (7,34,'Skirmish Warfare Specialist'),
    (7,34,'Warfare Link Specialist'),
    (7,34,'Wing Command'),
    (7,35,'Analytical Mind'),
    (7,35,'Clarity'),
    (7,35,'Eidetic Memory'),
    (7,35,'Empathy'),
    (7,35,'Focus'),
    (7,35,'Instant Recall'),
    (7,35,'Iron Will'),
    (7,35,'Learning'),
    (7,35,'Logic'),
    (7,35,'Presence'),
    (7,35,'Spatial Awareness') ,
    (7,36,'Armor Rigging'),
    (7,36,'Astronautics Rigging'),
    (7,36,'Battleship Construction'),
    (7,36,'Capital Remote Armor Repair Systems'),
    (7,36,'Capital Remote Hull Repair Systems'),
    (7,36,'Captial Repair Systems'),
    (7,36,'Capital Ship Construction'),
    (7,36,'Cruiser Construction'),
    (7,36,'Drones Rigging'),
    (7,36,'Electronic Superiority Rigging'),
    (7,36,'EM Armor Compensation'),
    (7,36,'Energy Weapon Rigging'),
    (7,36,'Explosive Armor Compensation'),
    (7,36,'Frigate Construction'),
    (7,36,'Hull Upgrades'),
    (7,36,'Hybrid Weapon Rigging'),
    (7,36,'Industrial Construction'),
    (7,36,'Jury Rigging'),
    (7,36,'Kinetic Armor Compensation'),
    (7,36,'Launcher Rigging'),
    (7,36,'Mechanic'),
    (7,36,'Nanite Interfacing'),
    (7,36,'Nanite Operation'),
    (7,36,'Outpost Construction'),
    (7,36,'Projectile Weapon Rigging'),
    (7,36,'Remote Armor Repair Systems'),
    (7,36,'Remote Hull Repair Systems'),
    (7,36,'Repair Systems'),
    (7,36,'Salvaging'),
    (7,36,'Shield Rigging'),
    (7,36,'Tactical Logistics Reconfiguration'),
    (7,36,'Thermic Armor Compensation'),
    (7,37,'Bomb Deployment'),
    (7,37,'Citadel Torpedoes'),
    (7,37,'Cruise Missile Specialization'),
    (7,37,'Cruise Missiles'),
    (7,37,'Defender Missiles'),
    (7,37,'FoF Missiles'),
    (7,37,'Guided Missile Precision'),
    (7,37,'Heavy Assault Missile Specialization'),
    (7,37,'Heavy Assault Missiles'),
    (7,37,'Heavy Missile Specialization'),
    (7,37,'Heavy Missiles'),
    (7,37,'Missile Bombardment'),
    (7,37,'Missile Launcher Operation'),
    (7,37,'Missile Projection'),
    (7,37,'Rapid Launch'),
    (7,37,'Rockets'),
    (7,37,'Rocket Specialization'),
    (7,37,'Standard Missile Specialization'),
    (7,37,'Standard Missiles'),
    (7,37,'Target Navigation Prediction'),
    (7,37,'Torpedo Specialization'),
    (7,37,'Torpedoes'),
    (7,37,'Warhead Upgrades'),
    (7,38,'Acceleration Control'),
    (7,38,'Afterburner'),
    (7,38,'Evasive Maneuvering'),
    (7,38,'Fuel Conservation'),
    (7,38,'High Speed Maneuvering'),
    (7,38,'Jump Drive Calibration'),
    (7,38,'Jump Drive Operation'),
    (7,38,'Jump Fuel Conservation'),
    (7,38,'Navigation'),
    (7,38,'Warp Drive Operation'),
    (7,39,'Advanced Laboratory Operation'),
    (7,39,'Amarr Encryption Methods'),
    (7,39,'Amarrian Starship Engineering'),
    (7,39,'Angel Encryption Methods'),
    (7,39,'Archaeology'),
    (7,39,'Astrogeology'),
    (7,39,'Astrometric Pinpointing'),
    (7,39,'Astrometric Acquisition'),
    (7,39,'Astrometric Rangefinding'),
    (7,39,'Astrometrics'),
    (7,39,'Astronautic Engineering'),
    (7,39,'Biology'),
    (7,39,'Blood Raider Encryption Methods'),
    (7,39,'Caldari Encryption Methods'),
    (7,39,'Caldari Starship Engineering'),
    (7,39,'Cloning Facility Operation'),
    (7,39,'Cybernetics'),
    (7,39,'Doomsday Operation'),
    (7,39,'Electromagnetic Physics'),
    (7,39,'Electronic Engineering'),
    (7,39,'Gallente Encryption Methods'),
    (7,39,'Gallentean Starship Engineering'),
    (7,39,'Genetic Engineering'),
    (7,39,'Graviton Physics'),
    (7,39,'Gunnery Interfaces'),
    (7,39,'Guristas Encryption Methods'),
    (7,39,'Hacking'),
    (7,39,'High Energy Physics'),
    (7,39,'Hydromagnetic Physics'),
    (7,39,'Infomorph Psychology'),
    (7,39,'Jump Portal Generation'),
    (7,39,'Laboratory Operation'),
    (7,39,'Laser Physics'),
    (7,39,'Mechanical Engineering'),
    (7,39,'Metallurgy'),
    (7,39,'Minmatar Encryption Methods'),
    (7,39,'Minmatar Starship Engineering'),
    (7,39,'Mnemonics'),
    (7,39,'Molecular Engineering'),
    (7,39,'Nanite Control'),
    (7,39,'Nanite Engineering'),
    (7,39,'Neurotoxin Recovery'),
    (7,39,'Nuclear Physics'),
    (7,39,'Plasma Physics'),
    (7,39,'Quantum Physics'),
    (7,39,'Research'),
    (7,39,'Research Project Management'),
    (7,39,'Rocket Science'),
    (7,39,'Science'),
    (7,39,'Scientific Networking'),
    (7,39,'Serpentis Encryption Methods'),
    (7,39,'Sleeper Technology'),
    (7,39,'Takmahl Technology'),
    (7,39,'Talocan Technology'),
    (7,39,'Thermodynamics'),
    (7,39,'Yan Jung Technology'),
    (7,40,'Bureaucratic Connections'),
    (7,40,'Connections'),
    (7,40,'Criminal Connections'),
    (7,40,'DED Connections'),
    (7,40,'Diplomacy'),
    (7,40,'Fast Talk'),
    (7,40,'Financial Connections'),
    (7,40,'High Tech Connections'),
    (7,40,'Labor Connections'),
    (7,40,'Military Connections'),
    (7,40,'Negotiation'),
    (7,40,'Political Connections'),
    (7,40,'Social'),
    (7,40,'Trade Connections'),
    (7,41,'Advanced Spaceship Command'),
    (7,41,'Amarr Battleship'),
    (7,41,'Amarr Carrier'),
    (7,41,'Amarr Cruiser'),
    (7,41,'Amarr Dreadnought'),
    (7,41,'Amarr Freighter'),
    (7,41,'Amarr Frigate'),
    (7,41,'Amarr Industrial'),
    (7,41,'Amarr Strategic Cruiser'),
    (7,41,'Amarr Titan'),
    (7,41,'Assault Ships'),
    (7,41,'Battlecruisers'),
    (7,41,'Black Ops'),
    (7,41,'Caldari Battleship'),
    (7,41,'Caldari Carrier'),
    (7,41,'Caldari Cruiser'),
    (7,41,'Caldari Dreadnought'),
    (7,41,'Caldari Freighter'),
    (7,41,'Caldari Frigate'),
    (7,41,'Caldari Industrial'),
    (7,41,'Caldari Strategic Cruiser'),
    (7,41,'Caldari Titan'),
    (7,41,'Capital Industrial Ships'),
    (7,41,'Capital Ships'),
    (7,41,'Command Ships'),
    (7,41,'Covert Ops'),
    (7,41,'Destroyers'),
    (7,41,'Electronic Attack Ships'),
    (7,41,'Exhumers'),
    (7,41,'Gallente Battleship'),
    (7,41,'Gallente Carrier'),
    (7,41,'Gallente Cruiser'),
    (7,41,'Gallente Dreadnought'),
    (7,41,'Gallente Freighter'),
    (7,41,'Gallente Frigate'),
    (7,41,'Gallente Industrial'),
    (7,41,'Gallente Strategic Cruiser'),
    (7,41,'Gallente Titan'),
    (7,41,'Heavy Assault Ships'),
    (7,41,'Heavy Interdictors'),
    (7,41,'Interceptors'),
    (7,41,'Interdictors'),
    (7,41,'Jump Freighters'),
    (7,41,'Logistics'),
    (7,41,'Marauders'),
    (7,41,'Mining Barge'),
    (7,41,'Minmatar Battleship'),
    (7,41,'Minmatar Carrier'),
    (7,41,'Minmatar Cruiser'),
    (7,41,'Minmatar Dreadnought'),
    (7,41,'Minmatar Freighter'),
    (7,41,'Minmatar Frigate'),
    (7,41,'Minmatar Industrial'),
    (7,41,'Minmatar Strategic Cruiser'),
    (7,41,'Minmatar Titan'),
    (7,41,'Recon Ships'),
    (7,41,'Spaceship Command'),
    (7,41,'Transport Ships'),
    (7,42,'Amarr Defensive Systems'),
    (7,42,'Amarr Electronic Systems'),
    (7,42,'Amarr Engineering Systems'),
    (7,42,'Amarr Offensive Systems'),
    (7,42,'Amarr Propulsion Systems'),
    (7,42,'Caldari Defensive Systems'),
    (7,42,'Caldari Electronic Systems'),
    (7,42,'Caldari Engineering Systems'),
    (7,42,'Caldari Offensive Systems'),
    (7,42,'Caldari Propulsion Systems'),
    (7,42,'Gallente Defensive Systems'),
    (7,42,'Gallente Electronic Systems'),
    (7,42,'Gallente Engineering Systems'),
    (7,42,'Gallente Offensive Systems'),
    (7,42,'Gallente Propulsion Systems'),
    (7,42,'Minmatar Defensive Systems'),
    (7,42,'Minmatar Electronic Systems'),
    (7,42,'Minmatar Engineering Systems'),
    (7,42,'Minmatar Offensive Systems'),
    (7,42,'Minmatar Propulsion Systems'),
    (7,43,'Accounting'),
    (7,43,'Broker Relations'),
    (7,43,'Contracting'),
    (7,43,'Corporation Contracting'),
    (7,43,'Daytrading'),
    (7,43,'Margin Trading'),
    (7,43,'Marketing'),
    (7,43,'Procurement'),
    (7,43,'Retail'),
    (7,43,'Trade'),
    (7,43,'Tycoon'),
    (7,43,'Visibility'),
    (7,43,'Wholesale');
