ALTER TABLE item_type_table AUTO_INCREMENT = 1;

INSERT INTO item_type_table ('category_id', 'type_name') VALUES
    (1,'Veldspar'),
    (1,'Scordite'),
    (1,'Plagioclase'),
    (1,'Pyroxeres'),
    (1,'Omber'),
    (1,'Kernite'),
    (1,'Jaspet'),
    (1,'Hemorphite'),
    (1,'Hedbergite'),
    (1,'Gneiss'),
    (1,'Dark Ochre'),
    (1,'Crokite'),
    (1,'Spodumain'),
    (1,'Bistot'),
    (1,'Arkonor'),
    (1,'Mercoxit'),
    (1,'Minerals'),
    (2,'Gas Clouds'),
    (3,'Ice Ore'),
    (3,'Ice Products'),
    (4,'Raw Materials'),
    (4,'Processed Materials'),
    (4,'Advanced Materials'),
    (5,'Fullerenes'),
    (6,'Alloys & Compounds'),
    (6,'Salvaged Materials'),
    (6,'Ancient Salvaged Materials'),
    (7,'Corporation Management'),
    (7,'Drones'),
    (7,'Electronics'),
    (7,'Engineering'),
    (7,'Gunnery'),
    (7,'Industry'),
    (7,'Leadership'),
    (7,'Learning'),
    (7,'Mechanic'),
    (7,'Missiles'),
    (7,'Navigation'),
    (7,'Science'),
    (7,'Social'),
    (7,'Spaceship Command'),
    (7,'Subsystems'),
    (7,'Trade');
